repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # check for latest later
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0  # check for latest later
    hooks:
      - id: ruff
      - id: ruff-format
